"""Alembic

Revision ID: 6505f7f9e3ea
Revises: 
Create Date: 2023-09-22 16:32:16.776255

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel
from src.repository import create_roles, create_admin


# revision identifiers, used by Alembic.
revision = '6505f7f9e3ea'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    create_roles()
    create_admin()
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###